
export interface JournalTemplate {
    name: string;
    debit: string[];
    credit: string[];
}

export const journalTemplates: JournalTemplate[] = [
    { name: "Cash sale of goods", debit: ["Cash"], credit: ["Sales Revenue"] },
    { name: "Purchase of inventory on credit", debit: ["Purchases"], credit: ["Accounts Payable"] },
    { name: "Payment of rent", debit: ["Rent Expense"], credit: ["Cash"] },
    { name: "Received cash for services rendered", debit: ["Cash"], credit: ["Service Revenue"] },
    { name: "Purchased office supplies with cash", debit: ["Office Supplies"], credit: ["Cash"] },
    { name: "Customer pays for a previous credit sale", debit: ["Cash"], credit: ["Accounts Receivable"] },
    { name: "Payment to a supplier for a previous credit purchase", debit: ["Accounts Payable"], credit: ["Cash"] },
    { name: "Owner invests cash in the business", debit: ["Cash"], credit: ["Capital / Owner's Equity"] },
    { name: "Owner withdraws cash for personal use", debit: ["Drawings / Owner's Equity"], credit: ["Cash"] },
    { name: "Paid employee salaries", debit: ["Salaries Expense"], credit: ["Cash"] },
    { name: "Purchased equipment with a bank loan", debit: ["Equipment"], credit: ["Bank Loan"] },
    { name: "Paid electricity bill", debit: ["Utilities Expense"], credit: ["Cash"] },
    { name: "Issued a check to a creditor", debit: ["Accounts Payable"], credit: ["Cash"] },
    { name: "Received cash from a debtor", debit: ["Cash"], credit: ["Accounts Receivable"] },
    { name: "Depreciation of equipment", debit: ["Depreciation Expense"], credit: ["Accumulated Depreciation"] },
    { name: "Received interest on a bank deposit", debit: ["Cash"], credit: ["Interest Revenue"] },
    { name: "Paid interest on a bank loan", debit: ["Interest Expense"], credit: ["Cash"] },
    { name: "Sale of goods on credit", debit: ["Accounts Receivable"], credit: ["Sales Revenue"] },
    { name: "Returned defective goods to a supplier", debit: ["Accounts Payable"], credit: ["Purchases Returns"] },
    { name: "A customer returns goods they purchased on credit", debit: ["Sales Returns & Allowances"], credit: ["Accounts Receivable"] },
    { name: "Paid for advertising", debit: ["Advertising Expense"], credit: ["Cash"] },
    { name: "Insurance premium paid for the year", debit: ["Prepaid Insurance"], credit: ["Cash"] },
    { name: "Paid for legal and professional fees", debit: ["Legal Fees Expense"], credit: ["Cash"] },
    { name: "Purchased a new vehicle for cash", debit: ["Vehicle"], credit: ["Cash"] },
    { name: "Sold an old machine for cash", debit: ["Cash"], credit: ["Machinery / Equipment"] },
    { name: "Borrowed cash from a bank", debit: ["Cash"], credit: ["Bank Loan"] },
    { name: "Repaid a portion of a bank loan", debit: ["Bank Loan"], credit: ["Cash"] },
    { name: "Received commission revenue", debit: ["Cash"], credit: ["Commission Revenue"] },
    { name: "Paid for repairs and maintenance", debit: ["Repairs & Maintenance Expense"], credit: ["Cash"] },
    { name: "A new partner contributes equipment to the business", debit: ["Equipment"], credit: ["Partner's Capital"] },
    { name: "Purchased a building with a mortgage", debit: ["Building"], credit: ["Mortgage Payable"] },
    { name: "Paid rent in advance for 3 months", debit: ["Prepaid Rent"], credit: ["Cash"] },
    { name: "Recorded accrued salaries at year-end", debit: ["Salaries Expense"], credit: ["Salaries Payable"] },
    { name: "Billed a client for services on credit", debit: ["Accounts Receivable"], credit: ["Service Revenue"] },
    { name: "Cash deposit into bank account", debit: ["Bank"], credit: ["Cash"] },
    { name: "Cash withdrawal from bank account", debit: ["Cash"], credit: ["Bank"] },
    { name: "Paid a dividend to shareholders", debit: ["Dividends"], credit: ["Cash"] },
    { name: "Received cash from the sale of an asset at a loss", debit: ["Cash", "Loss on Sale of Asset"], credit: ["Asset"] },
    { name: "Purchased new furniture on credit", debit: ["Furniture"], credit: ["Accounts Payable"] },
    { name: "Paid property taxes", debit: ["Property Tax Expense"], credit: ["Cash"] },
    { name: "Received a check from a client for services", debit: ["Bank"], credit: ["Service Revenue"] },
    { name: "Made an investment in another company", debit: ["Investment"], credit: ["Bank"] },
    { name: "Received dividend income from an investment", debit: ["Cash"], credit: ["Dividend Income"] },
    { name: "Issued shares of stock for cash", debit: ["Cash"], credit: ["Share Capital"] },
    { name: "Recorded bad debt expense (estimated)", debit: ["Bad Debt Expense"], credit: ["Allowance for Doubtful Accounts"] },
    { name: "Wrote off an uncollectible account", debit: ["Allowance for Doubtful Accounts"], credit: ["Accounts Receivable"] },
    { name: "Paid an overdue invoice with a discount received", debit: ["Accounts Payable"], credit: ["Cash", "Purchase Discounts"] },
    { name: "Customer pays early and receives a discount", debit: ["Cash", "Sales Discounts"], credit: ["Accounts Receivable"] },
    { name: "Received a grant from the government", debit: ["Cash"], credit: ["Grant Revenue"] },
    { name: "Paid for transportation of goods", debit: ["Freight-in Expense"], credit: ["Cash"] },
    { name: "Sold goods to a customer on credit at a loss", debit: ["Accounts Receivable", "Loss on Sale"], credit: ["Sales Revenue", "Inventory"] },
    { name: "Purchased raw materials on credit", debit: ["Raw Materials"], credit: ["Accounts Payable"] },
    { name: "Paid for factory wages", debit: ["Factory Wages"], credit: ["Cash"] },
    { name: "Transferred finished goods to inventory", debit: ["Finished Goods Inventory"], credit: ["Work-in-Progress Inventory"] },
    { name: "Paid for a patent", debit: ["Patent"], credit: ["Cash"] },
    { name: "Amortization of a patent", debit: ["Amortization Expense"], credit: ["Patent"] },
    { name: "Issued a bond to raise capital", debit: ["Cash"], credit: ["Bonds Payable"] },
    { name: "Paid bond interest", debit: ["Interest Expense"], credit: ["Cash"] },
    { name: "Recorded accrued interest on a loan at year-end", debit: ["Interest Expense"], credit: ["Interest Payable"] },
    { name: "Customer prepays for services", debit: ["Cash"], credit: ["Unearned Revenue"] },
    { name: "Earned a portion of unearned revenue", debit: ["Unearned Revenue"], credit: ["Service Revenue"] },
    { name: "Paid for telephone and internet bills", debit: ["Communications Expense"], credit: ["Cash"] },
    { name: "Received a refund from a supplier", debit: ["Cash"], credit: ["Purchases"] },
    { name: "Paid for a subscription to software", debit: ["Subscription Expense"], credit: ["Cash"] },
    { name: "Received a bill for water", debit: ["Utilities Expense"], credit: ["Accounts Payable"] },
    { name: "Paid the water bill received earlier", debit: ["Accounts Payable"], credit: ["Cash"] },
    { name: "Sale of land for cash", debit: ["Cash"], credit: ["Land"] },
    { name: "Sold shares of another company at a profit", debit: ["Cash"], credit: ["Investment", "Gain on Sale of Investment"] },
    { name: "Made a charitable donation", debit: ["Donations Expense"], credit: ["Cash"] },
    { name: "Paid for vehicle fuel", debit: ["Fuel Expense"], credit: ["Cash"] },
    { name: "Recorded an inventory write-down", debit: ["Loss on Inventory Write-down"], credit: ["Inventory"] },
    { name: "Paid for a business license", debit: ["License Expense"], credit: ["Cash"] },
    { name: "Received a loan from a director", debit: ["Cash"], credit: ["Loan from Director"] },
    { name: "Paid back the loan from a director", debit: ["Loan from Director"], credit: ["Cash"] },
    { name: "Paid for payroll taxes", debit: ["Payroll Tax Expense"], credit: ["Cash"] },
    { name: "A debtor's check bounces", debit: ["Accounts Receivable"], credit: ["Cash"] },
    { name: "Recorded a provision for warranty repairs", debit: ["Warranty Expense"], credit: ["Provision for Warranty Repairs"] },
    { name: "Paid for transportation of sales", debit: ["Freight-out Expense"], credit: ["Cash"] },
    { name: "Purchased an intangible asset (e.g., goodwill)", debit: ["Goodwill"], credit: ["Cash"] },
    { name: "Received rent from a tenant", debit: ["Cash"], credit: ["Rent Revenue"] },
    { name: "Paid for customs duties on imported goods", debit: ["Customs Duty Expense"], credit: ["Cash"] },
    { name: "Recorded accrued rent at year-end", debit: ["Rent Receivable"], credit: ["Rent Revenue"] },
    { name: "Purchased a small piece of machinery for cash", debit: ["Machinery"], credit: ["Cash"] },
    { name: "Received a credit note from a supplier", debit: ["Accounts Payable"], credit: ["Purchases"] },
    { name: "Sold an asset to a customer on credit", debit: ["Accounts Receivable"], credit: ["Asset"] },
    { name: "Made a provision for bad debt", debit: ["Bad Debt Expense"], credit: ["Provision for Bad Debts"] },
    { name: "Received a government subsidy", debit: ["Cash"], credit: ["Government Subsidy Revenue"] },
    { name: "Paid for an external audit", debit: ["Audit Fees Expense"], credit: ["Cash"] },
    { name: "Purchased a trademark", debit: ["Trademark"], credit: ["Cash"] },
    { name: "Amortization of a trademark", debit: ["Amortization Expense"], credit: ["Trademark"] },
    { name: "Paid for legal settlement", debit: ["Legal Settlement Expense"], credit: ["Cash"] },
    { name: "Recorded a deferred tax liability", debit: ["Income Tax Expense"], credit: ["Deferred Tax Liability"] },
    { name: "Received a deferred tax asset", debit: ["Deferred Tax Asset"], credit: ["Income Tax Expense"] },
    { name: "Paid cash to reduce a mortgage", debit: ["Mortgage Payable"], credit: ["Cash"] },
    { name: "Paid for a marketing campaign", debit: ["Marketing Expense"], credit: ["Cash"] },
    { name: "Purchased inventory from a foreign supplier on credit", debit: ["Purchases"], credit: ["Accounts Payable"] },
    { name: "Paid a deposit to a supplier", debit: ["Deposits"], credit: ["Cash"] },
    { name: "Received a deposit from a customer", debit: ["Cash"], credit: ["Customer Deposits"] },
    { name: "Transferred cash from savings to checking account", debit: ["Checking Account"], credit: ["Savings Account"] },
    { name: "Declared and paid a dividend", debit: ["Retained Earnings"], credit: ["Cash"] },
    { name: "Purchase of treasury stock", debit: ["Treasury Stock"], credit: ["Cash"] },
    { name: "Resale of treasury stock at a profit", debit: ["Cash"], credit: ["Treasury Stock", "Paid-in Capital from Treasury Stock"] },
    { name: "Resale of treasury stock at a loss", debit: ["Cash", "Paid-in Capital from Treasury Stock"], credit: ["Treasury Stock"] },
    { name: "Paid for a corporate tax bill", debit: ["Income Tax Expense"], credit: ["Cash"] },
    { name: "Recorded income tax payable at year-end", debit: ["Income Tax Expense"], credit: ["Income Tax Payable"] },
    { name: "Accrued interest on a note receivable", debit: ["Interest Receivable"], credit: ["Interest Revenue"] },
    { name: "Received a payment for a note receivable", debit: ["Cash"], credit: ["Notes Receivable"] },
    { name: "Provided services on credit and collected sales tax", debit: ["Accounts Receivable"], credit: ["Service Revenue", "Sales Tax Payable"] },
    { name: "Paid collected sales tax to the government", debit: ["Sales Tax Payable"], credit: ["Cash"] },
    { name: "Issued a check for a travel advance", debit: ["Travel Advances"], credit: ["Cash"] },
    { name: "Employee submits expense report for travel", debit: ["Travel Expense"], credit: ["Travel Advances", "Cash"] },
    { name: "Purchased a copyright", debit: ["Copyright"], credit: ["Cash"] },
    { name: "Amortization of a copyright", debit: ["Amortization Expense"], credit: ["Copyright"] },
    { name: "Paid for a website domain and hosting", debit: ["Website Expense"], credit: ["Cash"] },
    { name: "Recorded an uncollectible note receivable", debit: ["Loss on Uncollectible Note"], credit: ["Notes Receivable"] },
    { name: "Received cash for a royalty payment", debit: ["Cash"], credit: ["Royalty Revenue"] },
    { name: "Paid for research and development costs", debit: ["R&D Expense"], credit: ["Cash"] },
    { name: "Paid a performance bonus to an employee", debit: ["Bonus Expense"], credit: ["Cash"] },
    { name: "A customer prepays for goods", debit: ["Cash"], credit: ["Unearned Revenue"] },
    { name: "Delivered goods to a customer who prepaid", debit: ["Unearned Revenue"], credit: ["Sales Revenue"] },
    { name: "Incurred a loss from a fire", debit: ["Loss from Fire"], credit: ["Inventory", "Equipment", "etc."] },
    { name: "Received insurance proceeds for fire loss", debit: ["Cash"], credit: ["Loss from Fire"] },
    { name: "Purchased merchandise with a note payable", debit: ["Inventory"], credit: ["Notes Payable"] },
    { name: "Repaid a note payable with interest", debit: ["Notes Payable", "Interest Expense"], credit: ["Cash"] },
    { name: "Paid for a vehicle lease", debit: ["Lease Expense"], credit: ["Cash"] },
    { name: "Sold an asset with a gain", debit: ["Cash"], credit: ["Asset", "Gain on Sale of Asset"] },
    { name: "Paid for customs duties on imported goods", debit: ["Customs Duty Expense"], credit: ["Cash"] },
    { name: "Recorded prepaid insurance expired", debit: ["Insurance Expense"], credit: ["Prepaid Insurance"] },
    { name: "Paid for a software license", debit: ["Software License Expense"], credit: ["Cash"] },
    { name: "Received a refund from a vendor", debit: ["Cash"], credit: ["Accounts Payable"] },
    { name: "Recorded an impairment of goodwill", debit: ["Impairment Loss"], credit: ["Goodwill"] },
    { name: "Paid for bank charges", debit: ["Bank Charges Expense"], credit: ["Cash"] },
    { name: "Received a grant for capital expenditure", debit: ["Cash"], credit: ["Deferred Grant Income"] },
    { name: "Amortization of deferred grant income", debit: ["Deferred Grant Income"], credit: ["Grant Revenue"] },
    { name: "Issued a stock dividend", debit: ["Retained Earnings"], credit: ["Common Stock", "Paid-in Capital in Excess of Par"] },
    { name: "Received cash for a land sale at a profit", debit: ["Cash"], credit: ["Land", "Gain on Sale of Land"] },
    { name: "Paid for a bond interest payment", debit: ["Bond Interest Expense"], credit: ["Cash"] },
    { name: "Purchased a franchise", debit: ["Franchise"], credit: ["Cash"] },
    { name: "Amortization of a franchise", debit: ["Amortization Expense"], credit: ["Franchise"] },
    { name: "Incurred an expense but did not pay yet", debit: ["Expense Name"], credit: ["Accrued Expenses Payable"] },
    { name: "Paid the accrued expense from earlier", debit: ["Accrued Expenses Payable"], credit: ["Cash"] },
    { name: "Received a donation", debit: ["Cash"], credit: ["Donations Revenue"] },
    { name: "Paid a subscription for a journal", debit: ["Subscription Expense"], credit: ["Cash"] },
    { name: "Paid for a repair on a vehicle", debit: ["Repairs Expense"], credit: ["Cash"] },
    { name: "Recorded sales returns and allowances", debit: ["Sales Returns & Allowances"], credit: ["Accounts Receivable"] },
    { name: "Accepted a note from a customer to replace their account receivable", debit: ["Notes Receivable"], credit: ["Accounts Receivable"] },
    { name: "Paid off a line of credit", debit: ["Line of Credit Payable"], credit: ["Cash"] },
    { name: "Drew on a line of credit", debit: ["Cash"], credit: ["Line of Credit Payable"] },
    { name: "Declared a dividend (not yet paid)", debit: ["Retained Earnings"], credit: ["Dividends Payable"] },
    { name: "Paid a declared dividend", debit: ["Dividends Payable"], credit: ["Cash"] },
    { name: "Issued preferred stock for cash", debit: ["Cash"], credit: ["Preferred Stock"] },
    { name: "Paid interest on preferred stock", debit: ["Dividends"], credit: ["Cash"] },
    { name: "Transferred cash to a petty cash fund", debit: ["Petty Cash"], credit: ["Cash"] },
    { name: "Replenished the petty cash fund", debit: ["Various Expenses"], credit: ["Cash"] },
    { name: "Recorded an inventory shortage discovered", debit: ["Inventory Shortage Expense"], credit: ["Inventory"] },
    { name: "Paid for research and development costs (capitalized)", debit: ["Intangible Asset - R&D"], credit: ["Cash"] },
    { name: "Amortization of R&D intangible asset", debit: ["Amortization Expense"], credit: ["Intangible Asset - R&D"] },
    { name: "Collected cash from a customer whose account was previously written off", debit: ["Cash"], credit: ["Bad Debt Recovery"] },
    { name: "Recorded payroll tax expense", debit: ["Payroll Tax Expense"], credit: ["Payroll Tax Payable"] },
    { name: "Paid payroll taxes", debit: ["Payroll Tax Payable"], credit: ["Cash"] },
    { name: "Received a customer's check that was dishonored", debit: ["Accounts Receivable"], credit: ["Cash"] },
    { name: "Issued a credit note to a customer for damaged goods", debit: ["Sales Returns & Allowances"], credit: ["Accounts Receivable"] },
    { name: "Purchased land and building together for cash", debit: ["Land", "Building"], credit: ["Cash"] },
    { name: "Paid for the installation of new equipment", debit: ["Equipment"], credit: ["Cash"] },
    { name: "Paid for a business travel expense", debit: ["Travel Expense"], credit: ["Cash"] },
    { name: "Received cash for a future event ticket sales", debit: ["Cash"], credit: ["Unearned Revenue"] },
    { name: "Event occurred, earned ticket revenue", debit: ["Unearned Revenue"], credit: ["Ticket Sales Revenue"] },
    { name: "Made a provision for a lawsuit", debit: ["Lawsuit Expense"], credit: ["Provision for Lawsuits"] },
    { name: "Paid cash to settle a lawsuit", debit: ["Provision for Lawsuits"], credit: ["Cash"] },
    { name: "Received a gift card sale", debit: ["Cash"], credit: ["Gift Card Liability"] },
    { name: "A customer redeems a gift card", debit: ["Gift Card Liability"], credit: ["Sales Revenue"] },
    { name: "Paid for a professional membership fee", debit: ["Membership Expense"], credit: ["Cash"] },
    { name: "Paid for a parking fine", debit: ["Fine and Penalty Expense"], credit: ["Cash"] },
    { name: "Received a long-term note from a customer", debit: ["Notes Receivable (long-term)"], credit: ["Accounts Receivable"] },
    { name: "Received interest on a note receivable", debit: ["Cash"], credit: ["Interest Revenue"] },
    { name: "Declared and paid a dividend from retained earnings", debit: ["Retained Earnings"], credit: ["Cash"] },
    { name: "Purchased a new vehicle with a down payment and a note payable", debit: ["Vehicle"], credit: ["Cash", "Notes Payable"] },
    { name: "Paid for a warehouse rental", debit: ["Warehouse Rent Expense"], credit: ["Cash"] },
    { name: "Received cash from a sale of a scrap material", debit: ["Cash"], credit: ["Other Revenue"] },
    { name: "Paid for a professional training course for employees", debit: ["Training Expense"], credit: ["Cash"] },
    { name: "Received a bill for legal services", debit: ["Legal Fees Expense"], credit: ["Accounts Payable"] },
    { name: "Paid a portion of a bank loan", debit: ["Bank Loan"], credit: ["Cash"] },
    { name: "Recorded an accrued expense at year-end", debit: ["Expense Name"], credit: ["Accrued Liabilities"] },
    { name: "Accrued utility costs", debit: ["Utilities Expense"], credit: ["Utilities Payable"] },
    { name: "Transferred work-in-progress to finished goods", debit: ["Finished Goods Inventory"], credit: ["Work-in-Progress Inventory"] },
    { name: "Received a refund from a vendor for a returned item", debit: ["Cash"], credit: ["Inventory"] },
    { name: "Purchased software for use for 5 years", debit: ["Software (Intangible Asset)"], credit: ["Cash"] },
    { name: "Amortization of the software asset", debit: ["Amortization Expense"], credit: ["Software (Intangible Asset)"] },
    { name: "Paid for a license fee", debit: ["License Fee Expense"], credit: ["Cash"] },
    { name: "Incurred a loss on the disposal of a fixed asset", debit: ["Cash", "Accumulated Depreciation", "Loss on Disposal of Asset"], credit: ["Asset"] },
    { name: "Received a bill from a vendor for goods", debit: ["Purchases"], credit: ["Accounts Payable"] },
    { name: "Paid the vendor for goods received earlier", debit: ["Accounts Payable"], credit: ["Cash"] },
    { name: "Received cash from a customer who was previously given a discount", debit: ["Cash", "Sales Discounts"], credit: ["Accounts Receivable"] },
    { name: "Recorded a provision for doubtful debts", debit: ["Bad Debt Expense"], credit: ["Provision for Doubtful Debts"] },
    { name: "Wrote off a bad debt from the provision", debit: ["Provision for Doubtful Debts"], credit: ["Accounts Receivable"] },
    { name: "Paid for research and development that is expensed immediately", debit: ["R&D Expense"], credit: ["Cash"] },
    { name: "Received rent for a sub-leased property", debit: ["Cash"], credit: ["Rent Revenue"] },
    { name: "Paid for a marketing study", debit: ["Marketing Expense"], credit: ["Cash"] },
    { name: "Declared a stock dividend", debit: ["Retained Earnings"], credit: ["Common Stock"] },
    { name: "Issued new shares in exchange for land", debit: ["Land"], credit: ["Common Stock"] },
];
